# Generated by Django 3.0.8 on 2020-08-28 10:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produce', '0004_auto_20200827_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
