# Generated by Django 3.0.8 on 2020-09-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produce', '0009_auto_20200901_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
