# Generated by Django 3.0.8 on 2020-09-08 13:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produce', '0010_auto_20200901_1325'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_order_orderproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProduct',
            new_name='OrderProduce',
        ),
    ]
